format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$conda\
[ ï¡ ](fg:#674ea7)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
format = "[$user ]($style)"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false # Disabled by default
format = "[$symbol]($style)"
[os.symbols]
Arch = "ó°£‡ "
Macos = "î˜µ "
Ubuntu = "ïŒ› "
Unknown = "ï™ "
Windows = "î˜ª "

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Workspaces" = "ï‘ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[git_branch]
symbol = "ï˜"
format = "[ $symbol $branch ]($style)"

[git_status]
format = "[$all_status$ahead_behind]($style)"
conflicted = "[=$count ]"
stashed = "[ï…•$count ](#3d85c6)"
deleted = "[âœ˜$count ](#f08080)"
renamed = "[Â»$count ](#86BBD8)"
modified = "[!$count ](#7fb2b2)"
staged = "[+$count ](#86BBD8)"
untracked = "[?$count ](#9cd26d)"
ahead = 'â‡¡$count '
diverged = 'â‡•â‡¡$ahead_countâ‡£$behind_count '
behind = 'â‡£$count '

[conda]
symbol = "ğŸ…’ "
format = "[$symbol$environment]($style) "
style = "bold green"
ignore_base = true

